export const umed = [
    { label: 'UND' },
    { label: 'L' },
    { label: 'GAL' },
    { label: 'KG ' },
    { label: 'M3 ' },
    { label: 'TO ' },
    { label: 'G ' },
    { label: 'M ' },
    { label: 'ROL' },
    { label: 'MLL' },
    { label: 'PAA' },
    { label: 'KI' },
    { label: 'MEI' },
    { label: 'M2' },
    { label: 'TAB' },
    { label: 'LB' },
    { label: 'ML' },
    { label: 'FCO' }
]
export const descarticles = [
    {label:'ACARICIDAS'},
    {label:'ACC. COMUNIC. IMP'},
    {label:'ACC. COMUNICACIONES'},
    {label:'ACCESORIOS COMPUTO'},
    {label:'ACIDO HUMICO/FULVICO'},
    {label:'ACTIVO FIJO'},
    {label:'ARANDANO'},
    {label:'ART. SEG INDUSTRIAL'},
    {label:'ARTICULOS DE COMPUTO'},
    {label:'ARTICULOS DIVERSOS'},
    {label:'ARTICULOS LIMPIEZA'},
    {label:'ARTICULOS VIGILANCI'},
    {label:'BIOESTIMULANTE / M.C'},
    {label:'CABLEADO ESTRUCTUR.'},
    {label:'CARNES Y EMBUTIDOS'},
    {label:'CEREALES Y MENESTRAS'},
    {label:'COMBUSTIBLES'},
    {label:'COMPUTO'},
    {label:'CONFECCIONES-CALZADO'},
    {label:'ECONOMATO'},
    {label:'EMB ARA BOLSAS'},
    {label:'EMB ARA CAJAS'},
    {label:'EMB ARA CLAMSHEL PUN'},
    {label:'EMB ARA PARIHUELAS'},
    {label:'EMB COMUN ACCESORIOS'},
    {label:'EMB COMUN ETIQUETAS'},
    {label:'EMB COMUN PARIHUELAS'},
    {label:'EMB ESP ACCESORIOS'},
    {label:'EMB ESP PARIHUELAS'},
    {label:'EMB PALT ACCESORIOS'},
    {label:'EMB PALT ETIQUETAS'},
    {label:'EMB VID ACCESORIOS'},
    {label:'EMB VID ETIQUETAS'},
    {label:'EQUIPO DE COMUNICAC.'},
    {label:'FAJAS'},
    {label:'FAJAS IMP'},
    {label:'FERRETERIA'},
    {label:'FERTILIZANTES FOLIAR'},
    {label:'FERTILIZANTES SUELO.'},
    {label:'FILTROS'},
    {label:'FRUTOS Y HORTALIZAS'},
    {label:'FUNGICIDAS'},
    {label:'HERBICIDAS'},
    {label:'HERR.-ACC  AGRIC IMP'},
    {label:'HERRAMIENTA-ACC AGRI'},
    {label:'HERRAMIENTAS'},
    {label:'IMPRESORA CODI.BARRA'},
    {label:'IMPRESORA LASER'},
    {label:'IMPRESORA MATRICIAL'},
    {label:'IMPRESORA TINTA'},
    {label:'INS. QUIMICO CONTR.'},
    {label:'INS.AGRICOLA VAR IMP'},
    {label:'INS.AGRICOLA VARIOS'},
    {label:'INSECTICIDAS'},
    {label:'INSTRUMENTACION'},
    {label:'INSUMOS QUIMICOS.'},
    {label:'LACTEOS Y HUEVOS'},
    {label:'LICENCIAS'},
    {label:'LUBRICANTES'},
    {label:'MATERIAL CONSTRUC.'},
    {label:'MEDICINAS'},
    {label:'MOBILES'},
    {label:'MONITOR'},
    {label:'MUESTRAS'},
    {label:'NEUMATICOS'},
    {label:'NEUMATICOS IMP'},
    {label:'NOTEBOOK'},
    {label:'OTROS PLAGUICIDAS'},
    {label:'PC ESCRITORIO'},
    {label:'PERNOS Y TUERCAS'},
    {label:'PERNOS Y TUERCAS IMP'},
    {label:'PINTURAS Y AFINES'},
    {label:'R ELECTRIC ELECTRONI'},
    {label:'R.P.BATERIAS'},
    {label:'R.P.EPP'},
    {label:'RADIOS VHF/UHF'},
    {label:'REG. CRECIMIENTO IMP'},
    {label:'REGULADOR CRECIMIENT'},
    {label:'RELOJ MARCADOR'},
    {label:'REP. ELECTRONICO IMP'},
    {label:'REP. HIDRAULICA IMP'},
    {label:'REP. IMPLEMENTO IMP'},
    {label:'REP. MECANICOS IMP'},
    {label:'REP. TRACTORES IMP'},
    {label:'REP. VEHICULOS IMP'},
    {label:'REPUESTO IMPLEMENTO'},
    {label:'REPUESTOS COMPUTO'},
    {label:'REPUESTOS HIDRAULICA'},
    {label:'REPUESTOS MECANICOS'},
    {label:'REPUESTOS SIS. FRIO'},
    {label:'REPUESTOS TRACTORES'},
    {label:'REPUESTOS VARIOS'},
    {label:'REPUESTOS VARIOS IMP'},
    {label:'REPUESTOS VEHICULOS'},
    {label:'RESIDUOS NO PELIGROS'},
    {label:'RESIDUOS PELIGROSOS'},
    {label:'RODAMIENTOS'},
    {label:'SEMILLAS'},
    {label:'SERV Y SUBCONTRATA'},
    {label:'SERVICIOS NACIONALES'},
    {label:'SERVIDORES'},
    {label:'SOLDADURAS'},
    {label:'SUMINISTROS IMPRES.'},
    {label:'SUSTANCIAS AFINES'},
    {label:'UPS'},
    {label:'UTENSILIOS'},
    {label:'UTILES DE OFICINA'},
    {label:'VEGETALES Y FRUTAS'},
    {label:'VIVERES Y ENVASADOS'},
    
]